### ISSUE TITLE
number query return SQLITE_ERROR

### ISSUE THREAD

**Issue by arieffajargemilang** [4Q-s-r-o/call_log#26]
my code

`                    final Iterable<CallLogEntry> result = await CallLog.query(
                        number: '+62 852-3444-1010'
                    );`

log error

`E/flutter ( 7923): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(INTERNAL_ERROR, near "ANDmatched_number": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT formatted_number, number, type, date, duration, name, numbertype, numberlabel, matched_number, subscription_id FROM calls WHERE ((number LIKE '%+62 852-3444-1010%'ANDmatched_number LIKE '%+62 852-3444-1010%'ANDsubscription_id LIKE '%+62 852-3444-1010%') AND ((type != 4)) AND ((phone_account_hidden = 0))) ORDER BY date DESC, null, null)
E/flutter ( 7923): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 7923): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 7923): <asynchronous suspension>
E/flutter ( 7923): #2      CallLog.query (package:call_log/call_log.dart:67:40)
E/flutter ( 7923): <asynchronous suspension>
E/flutter ( 7923): #3      _DetailFuState.build.<anonymous closure> (package:sales/apps/follow_up/local_widgets/detail_fu.dart:176:59)
E/flutter ( 7923): <asynchronous suspension>
E/flutter ( 7923): 
`

help me

**Comment by AR553** [comment]
I just started getting this same error, basically what's happening is that I can only pass one query parameter 
`logs = await CL.CallLog.query(dateTimeFrom: from);`
and if I try to pass more than one parameter then the second parameter is not passed correctly
`logs = await CL.CallLog.query(dateTimeFrom: from, type: element);` and throws exception due to syntax error in the query being generated 


[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(INTERNAL_ERROR, near **"ANDtype"**: syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT formatted_number, number, type, date, duration, name, numbertype, numberlabel, matched_number, subscription_id FROM calls WHERE ((date > '1634065200000'**ANDtype** = '1') AND ((type != 4)) AND ((phone_account_hidden = 0)) AND ((mark_deleted = 0)) AND (type != 10)) ORDER BY date DESC, null, null)
E/flutter (19675): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (19675): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (19675): <asynchronous suspension>
E/flutter (19675): #2      CallLog.query (package:call_log/call_log.dart:67:40)
