### ISSUE TITLE
call Log ALREADY_RUNNING 

### ISSUE THREAD

**Issue by AhmedHussein22** [4Q-s-r-o/call_log#29]
not ask me for permission and get this error 
**`PlatformException(ALREADY_RUNNING, Method call was cancelled. One method call is already running, null, null)`**

**Comment by MartinHlavna** [comment]
Hi, 
can you share your code? This message is thrown when call log method is called twice. Logcat and flutter doctor output would also help.

**Comment by AhmedHussein22** [comment]
Hi,
**### this is my output from flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.62.2)
[√] Connected device (3 available)

• No issues found!

### **And this my code** 
`class CallLogInfo extends StatefulWidget {
  @override
  _CallLogInfoState createState() => _CallLogInfoState();
}

class _CallLogInfoState extends State<CallLogInfo> {
  CallLogs cl = new CallLogs();
  Future<Iterable<CallLogEntry>>? logs;
  var marginTop = 0.0;
  @override
  void initState() {
    super.initState();
    logs = CallLog.get();
   
  }


  @override
  Widget build(BuildContext context) {
    return  Scaffold(
        appBar: AppBar(
          title: Text("Call Log"),
          leading: InkWell(
            onTap: () {
              General.arrowBackFunction(context);
            },
            child: Icon(Icons.keyboard_backspace_outlined),
          ),
          backgroundColor: Color(0xFF154364),
          centerTitle: true,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(
              bottom: Radius.circular(20),
            ),
          ),
        ),
        body: Column(
          children: [
            SizedBox(
              height: marginTop
            ),
            FutureBuilder<Iterable<CallLogEntry>>(
                future: logs,
                builder: (context, snapshot) {
                  print("connectionState =============${snapshot.connectionState}");
                  print("data=============${snapshot.data}");
                  print("error=============${snapshot.error}");
                  print("hasData=============${snapshot.hasData}");

                  if (snapshot.connectionState == ConnectionState.done) {
                    //var entries = snapshot.data;
                    if (!snapshot.hasData) {
                      marginTop = 30.0;
                      return Center(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            CircularProgressIndicator(),
                            SizedBox(
                              width: 5,
                            ),
                            Text('Loading ...'),
                          ],
                        ),
                      );
                    }
                    return Expanded(
                      child: ListView.builder(
                        itemCount: snapshot.data!.length,
                        itemBuilder: (context, index) {
                          //
                          if (snapshot.data!.elementAt(index).simDisplayName == "SIM1") {
                            return Column(
                              children: [
                                Container(
                                  margin: EdgeInsets.symmetric(
                                      horizontal:
                                          General.widthOfScreen(context) * 0.03,
                                      vertical:
                                          General.heightOfScreen(context) *
                                              0.01),
                                  child: Row(
                                    children: [
                                      cl.getIcon(snapshot.data!.elementAt(index).callType!),
                                      SizedBox(
                                          width:
                                              General.widthOfScreen(context) *
                                                  0.04),
                                      Expanded(
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          crossAxisAlignment:
                                              CrossAxisAlignment.stretch,
                                          children: [
                                            //name and data
                                            Row(
                                              mainAxisAlignment:
                                                  MainAxisAlignment
                                                      .spaceBetween,
                                              children: [
                                                Container(
                                                  width: General.widthOfScreen(
                                                          context) *
                                                      0.4,
                                                  child: Text(
                                                    cl
                                                        .getTitle(snapshot.data!
                                                            .elementAt(index))
                                                        .toString(),
                                                    overflow:
                                                        TextOverflow.ellipsis,
                                                  ),
                                                ),
                                                Container(
                                                  child: Text(
                                                    cl.formatDate(new DateTime
                                                            .fromMillisecondsSinceEpoch(
                                                        snapshot.data!
                                                            .elementAt(index)
                                                            .timestamp!)),
                                                    style: TextStyle(
                                                        fontSize: 13.0),
                                                  ),
                                                ),
                                              ],
                                            ),
                                            SizedBox(height: 5),
                                            //duration and numder
                                            Row(
                                              mainAxisAlignment:
                                                  MainAxisAlignment
                                                      .spaceBetween,
                                              crossAxisAlignment:
                                                  CrossAxisAlignment.start,
                                              children: [
                                                Text(
                                                  "${cl.getTime(snapshot.data!.elementAt(index).duration!)}",
                                                  style:
                                                      TextStyle(fontSize: 13.0),
                                                ),
                                                Text(snapshot.data!
                                                        .elementAt(index)
                                                        .number ??
                                                    ""),
                                              ],
                                            ),
                                            SizedBox(height: 5),
                                            //sim and action
                                            Row(
                                              mainAxisAlignment:
                                                  MainAxisAlignment
                                                      .spaceBetween,
                                              children: [
                                                Text(snapshot.data!
                                                    .elementAt(index)
                                                    .simDisplayName
                                                    .toString()),
                                                Wrap(
                                                  children: [
                                                    // call
                                                    InkWell(
                                                      onTap: () =>
                                                          ContactFunction(
                                                                  context)
                                                              .launchCaller(
                                                                  snapshot
                                                                      .data!
                                                                      .elementAt(
                                                                          index)
                                                                      .number),
                                                      child: Icon(
                                                          CupertinoIcons
                                                              .phone_circle,
                                                          color:
                                                              Color(0xFF23C084),
                                                          size: 26),
                                                    ),

                                                    // add comments
                                                    SizedBox(
                                                      width: 8,
                                                    ),
                                                    InkWell(
                                                      onTap: () =>
                                                          General.routingPage(
                                                        context,
                                                        CommentScreen(
                                                          name: cl
                                                              .getTitle(snapshot
                                                                  .data!
                                                                  .elementAt(
                                                                      index))
                                                              .toString(),
                                                          phoneNumber: snapshot
                                                                  .data!
                                                                  .elementAt(
                                                                      index)
                                                                  .number ??
                                                              "",
                                                        ),
                                                      ),
                                                      child: Icon(
                                                        Icons.add_comment,
                                                        color:
                                                            Color(0xFF154364),
                                                        size: 26.0,
                                                      ),
                                                    ),
                                                    SizedBox(
                                                      width: 8,
                                                    ),
                                                    InkWell(
                                                      onTap: () {
                                                        General.routingPage(
                                                          context,
                                                          RequestLeadScreen(
                                                            name: cl
                                                                .getTitle(snapshot
                                                                    .data!
                                                                    .elementAt(
                                                                        index))
                                                                .toString(),
                                                            phoneNumber: snapshot
                                                                    .data!
                                                                    .elementAt(
                                                                        index)
                                                                    .number ??
                                                                "",
                                                          ),
                                                        );
                                                      },
                                                      child: Icon(
                                                          Icons
                                                              .add_circle_outline_sharp,
                                                          color:
                                                              Color(0xFF23C084),
                                                          size: 26.0),
                                                    ),
                                                  ],
                                                ),
                                              ],
                                            ),
                                          ],
                                        ),
                                      )
                                    ],
                                  ),
                                ),
                                Divider()
                              ],
                            );
                          } else {
                            return Container();
                          }
                        },
                      ),
                    );
                  } else {
                    return Center(child: General.customThreeBounce(context));
                  }
                }),
          ],
        ),
      
    );
  }
}`

### **And this is Debug Console When run**

> E/MethodChannel#sk.fourq.call_log( 1002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
E/DartMessenger( 1002): Uncaught exception in binary message listener
E/DartMessenger( 1002): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger( 1002): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/DartMessenger( 1002): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253)
E/DartMessenger( 1002): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger( 1002): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/DartMessenger( 1002): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger( 1002): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/DartMessenger( 1002): 	at android.os.Looper.loop(Looper.java:170)
E/DartMessenger( 1002): 	at android.app.ActivityThread.main(ActivityThread.java:7055)
E/DartMessenger( 1002): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 1002): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/DartMessenger( 1002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
I/flutter ( 1002): connectionState =============ConnectionState.waiting
I/flutter ( 1002): data=============null
I/flutter ( 1002): error=============null
I/flutter ( 1002): hasData=============false
I/flutter ( 1002): connectionState =============ConnectionState.done
I/flutter ( 1002): data=============null
I/flutter ( 1002): error=============PlatformException(ALREADY_RUNNING, Method call was cancelled. One method call is already running, null, null)
I/flutter ( 1002): hasData=============false
I/flutter ( 1002): connectionState =============ConnectionState.done
I/flutter ( 1002): data=============null
I/flutter ( 1002): error=============PlatformException(ALREADY_RUNNING, Method call was cancelled. One method call is already running, null, null)
I/flutter ( 1002): hasData=============false

**Comment by MartinHlavna** [comment]
Can you attach zip of simple project to reproduce the issue?

**Comment by MartinHlavna** [comment]
Can you try with ```3.2.2```?  It may be duplicate of #30

**Comment by tandacedric** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/13773515/157663174-9f688b21-eda3-4916-ad85-510319221628.png">
He forgot to call cleanup() here.
While waiting for him to modify, I will have to fork the project, modify it to use

**Comment by tandacedric** [comment]
You can use like this
  call_log:
    git: https://github.com/tandacedric/call_log.git

**Comment by MartinHlavna** [comment]
@tandacedric Hi,

are planning to open pull request with the fix? Since you already have fork and fix, you could be listed as an contributor :)
