### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Anujrana00956** [4Q-s-r-o/call_log#48]
i can face this issue anyone can slove this problem

E/flutter (26847): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method get on channel sk.fourq.call_log)
E/flutter (26847): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
E/flutter (26847): <asynchronous suspension>
E/flutter (26847): #1      CallLog.get (package:call_log/call_log.dart:12:39)
E/flutter (26847): <asynchronous suspension>
E/flutter (26847): #2      _startState._callLogs (package:untitled/start.dart:123:13)
E/flutter (26847): <asynchronous suspension>
E/flutter (26847): #3      _startState.build.<anonymous closure> (package:untitled/start.dart:239:19)
E/flutter (26847): <asynchronous suspension>
E/flutter (26847):

**Comment by MartinHlavna** [comment]
Does this issue persist on ```5.0.0```?
